# 訓練用とテスト用データの分割

## ライブラリのインポート

In [1]:
# train_test_splitモジュールをインポートします
import numpy as np
from sklearn.model_selection import train_test_split

## 分割するデータの作成

In [2]:
# １から100のデータが入っているオブジェクトを作成します
a = np.arange(1,101)

In [3]:
# 中身の確認
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [4]:
# 501から600までの数字が入っているオブジェクトを作成します
b = np.arange(501,601)
b

array([501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513,
       514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526,
       527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539,
       540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552,
       553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565,
       566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577, 578,
       579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591,
       592, 593, 594, 595, 596, 597, 598, 599, 600])

## データの分割


In [5]:
# 結果の確認
train_test_split(a)

[array([ 94,  63,  27,  37,  83,  86,  29,  77,  65,  13,  62,  31,  49,
         10,  75,  46,  91,  32,  67,  20,  79,  70,  15,  14,  69,  80,
          4,  95,  82,   6,  18,   7,  38,  19,  89,  73,  54,  23,  26,
         50,  87,  41,  24,  76,  68,  55,  97,  39,  92,  71,  59,  12,
         64,  45,   1,  40,  43,  34,  30,  93,  42,  53,  61,  28,  58,
         21,   9, 100,  60,  56,  33,  48,  81,  22,  74]),
 array([90, 72, 17,  5,  3,  2, 98, 84, 85, 25, 78, 96, 11, 88, 57, 66, 47,
        44, 16, 51, 99, 36,  8, 52, 35])]

# 単純な分割

In [18]:
a_train, a_test= train_test_split(a)

In [19]:
a_train.size, a_test.size

(75, 25)

In [20]:
a_train, a_test

(array([ 53,  57,   3,  14,  26,  38,  58,  61,  56,  35,  12,  60,  74,
        100,  86,  65,  45,  79,  23,  69,  40,  94,  52,  34,  78,  27,
         11,  54,  49,   5,  92,  17,   9,  48,   8,  30,  28,  13,  51,
         90,  32,  67,  20,  87,  36,  25,  83,  68,  18,  88,  84,  85,
         42,  70,   6,  76,  82,  77,  80,  64,  22,  47,  91,  37,  95,
         66,  21,  73,  98,  31,  29,  15,  43,  16,   2]),
 array([59, 50, 41, 97, 75, 55, 39, 44, 24, 93,  1, 19, 99, 81, 89, 72,  7,
        46, 63,  4, 62, 71, 96, 10, 33]))

# 分割の比率を変更することが可能

In [22]:
a_train, a_test = train_test_split(a, test_size=0.2)

In [23]:
a_train.size, a_test.size

(80, 20)

# 内容は実行するたびに変わるよ

In [25]:
a_train, a_test = train_test_split(a, test_size=0.2)
a_train, a_test

(array([63, 78, 72,  5, 43, 37, 19, 26, 86, 90, 49, 97, 93, 94, 23, 56,  4,
        75, 96, 27, 64, 38, 10, 50, 52, 95, 51, 76, 98, 81, 45, 57, 54, 60,
        15, 42,  8,  6, 13, 69, 91, 92, 61, 73,  3, 17, 53, 20, 62, 88, 77,
        40, 80, 14, 84, 16, 67, 87, 66,  1, 71, 41, 11, 44, 68, 58, 48, 79,
        89, 34, 21,  7, 12, 82, 36, 74, 55, 83, 33, 32]),
 array([ 35,  29,  70, 100,  25,  47,   2,  65,  30,  99,  22,  85,  59,
         46,  39,  18,  24,  31,   9,  28]))

In [26]:
a_train, a_test = train_test_split(a, test_size=0.2)
a_train, a_test

(array([ 66,  67,  60,  75,  24,  90,  80,  57,  99,  94,   7,  31,  39,
         54,   1,  11,  97,  10,  42,  59,  87,  29,  16,  98,  15,  58,
         84,  26,  62,  83,  27,   2,  82,  38,  50,  23,   4,  25,  78,
         63,  71,  77,  14,   3,  61,  53,   5,  30,  72,  86,  37,  56,
         48,  74,  91,  46,  69,  51,   6,  43,  33,  35,   9,  12,  32,
         76,  41,  73,  65,  70,  49,  36,  17,  22,  64,  44,  34,  18,
        100,  79]),
 array([55, 85, 95, 21,  8, 45, 28, 47, 19, 13, 96, 20, 81, 93, 68, 52, 88,
        89, 92, 40]))

# ランダム具合を固定することが可能 random_state = 42 などを入れてそれを変更しない場合

In [33]:
a_train, a_test = train_test_split(a, test_size=0.2, random_state=42)
a_train, a_test

(array([ 56,  89,  27,  43,  70,  16,  41,  97,  10,  73,  12,  48,  86,
         29,  94,   6,  67,  66,  36,  17,  50,  35,   8,  96,  28,  20,
         82,  26,  63,  14,  25,   4,  18,  39,   9,  79,   7,  65,  37,
         90,  57, 100,  55,  44,  51,  68,  47,  69,  62,  98,  80,  42,
         59,  49,  99,  58,  76,  33,  95,  60,  64,  85,  38,  30,   2,
         53,  22,   3,  24,  88,  92,  75,  87,  83,  21,  61,  72,  15,
         93,  52]),
 array([84, 54, 71, 46, 45, 40, 23, 81, 11,  1, 19, 31, 74, 34, 91,  5, 77,
        78, 13, 32]))

In [34]:
a_train, a_test = train_test_split(a, test_size=0.2, random_state=42)
a_train, a_test

(array([ 56,  89,  27,  43,  70,  16,  41,  97,  10,  73,  12,  48,  86,
         29,  94,   6,  67,  66,  36,  17,  50,  35,   8,  96,  28,  20,
         82,  26,  63,  14,  25,   4,  18,  39,   9,  79,   7,  65,  37,
         90,  57, 100,  55,  44,  51,  68,  47,  69,  62,  98,  80,  42,
         59,  49,  99,  58,  76,  33,  95,  60,  64,  85,  38,  30,   2,
         53,  22,   3,  24,  88,  92,  75,  87,  83,  21,  61,  72,  15,
         93,  52]),
 array([84, 54, 71, 46, 45, 40, 23, 81, 11,  1, 19, 31, 74, 34, 91,  5, 77,
        78, 13, 32]))

# ２つのデータに対しても同様にスプリットすることが可能

In [35]:
# 2つのデータ（オブジェクト）を4つに分割していきます
a_train, a_test, b_train, b_test = train_test_split(a, b, test_size=0.2, random_state=365)

In [36]:
a_train.size, a_test.size

(80, 20)

In [37]:
b_train.size, b_test.size

(80, 20)

## 結果の確認

In [38]:
# 形状を確認します
a_train.shape, a_test.shape

((80,), (20,))

In [39]:
# データの中身の確認
a_train

array([ 25,  32,  99,  73,  91,  66,   3,  59,  94,   1,   8,  15,  90,
        54,  31,  20,  77,  82,  30,  35,  95,  42,  38,   7,  11,  50,
        21,  48,   2,  17,  10,  58,  68,  43,  41,  16,  88,  72,  79,
       100,  80,  39,  24,  86,  22,  23,  62,  76,  18,  47,  55,  26,
        60,  19,  71,  64,  51,  63,  65,  28,  12,  78,  13,  44,  75,
        87,  40,   4,  29,  49,  37,  57,  27,  74,   6,  45,  92,  34,
        53,  83])

In [40]:
# データの中身の確認
a_test

array([ 9, 69, 81, 56, 33, 93, 84, 61, 46, 89, 85, 67, 97,  5, 70, 36, 98,
       96, 14, 52])

In [41]:
b_train.shape, b_test.shape

((80,), (20,))

In [42]:
b_train

array([525, 532, 599, 573, 591, 566, 503, 559, 594, 501, 508, 515, 590,
       554, 531, 520, 577, 582, 530, 535, 595, 542, 538, 507, 511, 550,
       521, 548, 502, 517, 510, 558, 568, 543, 541, 516, 588, 572, 579,
       600, 580, 539, 524, 586, 522, 523, 562, 576, 518, 547, 555, 526,
       560, 519, 571, 564, 551, 563, 565, 528, 512, 578, 513, 544, 575,
       587, 540, 504, 529, 549, 537, 557, 527, 574, 506, 545, 592, 534,
       553, 583])

In [43]:
b_test

array([509, 569, 581, 556, 533, 593, 584, 561, 546, 589, 585, 567, 597,
       505, 570, 536, 598, 596, 514, 552])