# 重回帰分析

## ライブラリのインポート

In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

from sklearn.linear_model import LinearRegression

## データの読み込み

In [6]:
data = pd.read_csv('1.02.Multiple-linear-regression.csv')

data.head()

SAT  Rand 1,2,3   GPA
0  1714           1  2.40
1  1664           3  2.52
2  1760           3  2.54
3  1685           3  2.74
4  1693           2  2.83

In [7]:
data.describe()

SAT  Rand 1,2,3        GPA
count    84.000000   84.000000  84.000000
mean   1845.273810    2.059524   3.330238
std     104.530661    0.855192   0.271617
min    1634.000000    1.000000   2.400000
25%    1772.000000    1.000000   3.190000
50%    1846.000000    2.000000   3.380000
75%    1934.000000    3.000000   3.502500
max    2050.000000    3.000000   3.810000

## 重回帰分析モデルを作成します

### 従属変数と独立変数を定義します

In [8]:
x = data[['SAT','Rand 1,2,3']]

y = data['GPA']

### 回帰

In [9]:
reg = LinearRegression()

reg.fit(x,y)

LinearRegression()

In [10]:
reg.coef_

array([ 0.00165354, -0.00826982])

In [11]:
reg.intercept_

0.29603261264909486

### Formula for Adjusted R^2
$R^2_{adj.}=1-(1-R^2)*\frac{n-1}{n-p-1}$

In [12]:
r2 = reg.score(x,y)

In [13]:
n=x.shape[0]
p=x.shape[1]

In [14]:
adjusted_rd = 1-(1-r2)*(n-1)/(n-p-1)
adjusted_rd


0.39203134825134023

# 結果としてわかったこと
+通常の決定係数に比較して、自由度修正済み決定係数のほうが小さいので「どこかの変数がおかしい」ということがなんとなくわかる。
+各変数に関してP値を計算して、その値が大きければその変数は従属変数に対して影響がないと判断できる

# Feature selection

In [15]:
from sklearn.feature_selection import f_regression
f_regression(x,y)

(array([56.04804786,  0.17558437]), array([7.19951844e-11, 6.76291372e-01]))

### 結果が何を意味しているか？ →　左（F値）、右（P値）

In [19]:
p_values = f_regression(x,y)[1]

In [20]:
p_values

array([7.19951844e-11, 6.76291372e-01])